name: trackmentalhealth
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  flutter_spinkit: ^5.2.1
  jwt_decoder: ^2.0.1
  visibility_detector: ^0.4.0+2
  timeago: ^3.7.0
  video_player: ^2.9.1
  just_audio: ^0.10.4
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  shared_preferences: ^2.2.2
  flutter_chat_ui: ^2.9.0
  flutter_chat_types: ^3.6.1
  uuid: ^4.5.1
  stomp_dart_client: ^1.0.0
  permission_handler: ^11.3.0
  firebase_core: ^3.4.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/LogoTMH.png
